### ISSUE TITLE
请教作者大大，支持Excel相关操作吗？

### ISSUE THREAD

**Issue by wang1589019** [ccpwcn/kgo#32]
请教作者大大，支持Excel相关操作吗？

**Comment by ccpwcn** [comment]
Excel操作是一个非常复杂的东西，仅仅依赖于标准库实现难度很大，而且已经有成熟的优秀的库了，没必要再做一套，推荐使用 https://github.com/qax-os/excelize 国人开发的优秀的Excel解析、读写库。
